### PR TITLE
Debug events

### PR DESCRIPTION
**Pull request by mihaimaruseac**

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Comment from within the PR

**Review by mihaimaruseac — COMMENTED** [review]
Comment as review

**Review by phythis424 — CHANGES_REQUESTED** [review]
Request changes

**Review by phythis424 — DISMISSED** [review]
Changes needed

**Review by phythis424 — DISMISSED** [review]

**Review by phythis424 — APPROVED** [review]

**Review by phythis424 — APPROVED** [review]

**Pull request merged**
